# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u5b57')),
            ],
            options={
                'db_table': 'game',
                'verbose_name': '\u6e38\u620f',
                'verbose_name_plural': '\u6e38\u620f',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u5b57')),
                ('age', models.IntegerField(max_length=5, verbose_name='\u5e74\u9f84')),
                ('pwd', models.CharField(max_length=10, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=20, verbose_name='\u90ae\u7bb1')),
                ('phone', models.IntegerField(max_length=11, verbose_name='\u624b\u673a\u53f7')),
                ('Introduction', models.TextField(verbose_name='\u7b80\u4ecb')),
            ],
            options={
                'abstract': False,
                'db_table': 'user',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forging.User', verbose_name='\u8d2d\u4e70\u8005'),
        ),
    ]
