# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head_portrait',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images', verbose_name='\u5934\u50cf'),
            preserve_default=False,
        ),
    ]
